#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import agent.tasks
import os

request = json.load(sys.stdin)

host = request.get("host", '')
le = request.get("lets_encrypt", False)
adminmail = request.get("adminmail",'')

# Setup environment for passbolt app
config = {
    "APP_FULL_BASE_URL": f"https://{host}",
    "DATASOURCES_DEFAULT_HOST": "127.0.0.1",
    "DATASOURCES_DEFAULT_USERNAME": "passbolt",
    "DATASOURCES_DEFAULT_PASSWORD": "passbolt",
    "DATASOURCES_DEFAULT_DATABASE": "passbolt",
    "ADMINMAIL": adminmail
}
agent.write_envfile('config.env', config)

# Setup environment for DB
db_config = {
    "MARIADB_ROOT_PASSWORD": "passbolt",
    "MARIADB_DATABASE": "passbolt",
    "MARIADB_USER": "passbolt",
    "MARIADB_PASSWORD": "passbolt",
}
agent.write_envfile('database.env', db_config)

# For later use and backup
with open('config.json', 'w') as cfp:
    cfp.write(json.dumps(request))

# Configure Traefik to route "/passbolt" path requests to the passbolt service
response = agent.tasks.run(
    agent_id=agent.resolve_agent_id('traefik@node'),
    action='set-route',
    data={
        'instance': os.environ['MODULE_ID'],
        'url':  'http://127.0.0.1:' + os.environ["TCP_PORT"],
        'http2https': True,
        'lets_encrypt': le,
        'host': host,
    },
)

# Check if traefik configuration has been successfull
agent.assert_exp(response['exit_code'] == 0)