#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# If the control reaches this step, the service can be enabled and started

touch smarthost.env

systemctl --user enable --now passbolt.service
systemctl --user enable passbolt-db.service
systemctl --user enable passbolt-app.service

systemctl --user try-restart passbolt-db.service passbolt-app.service
