#!/bin/bash

# Exit if admin url was already obtained
[[ -f admin_url.env ]] && exit 0

# Create temp file for catching the URL
tmpconf=$(mktemp admin_url.XXXXXX)
trap 'rm -f ${tmpconf}' EXIT

# Get environment variables
source config.env

# Create admin user
/usr/bin/podman exec passbolt-app /bin/bash \
  /usr/share/php/passbolt/bin/cake passbolt register_user \
  -u ${ADMINMAIL} \
  -f Passbolt \
  -l Admin \
  -r admin > ${tmpconf}

# Extract link out of admin link output, remove ANSI
userreg=$(tail -n1 ${tmpconf} | sed -e 's/\x1b\[[0-9;]*m//g')

# If the registration was successful put the ADMINURL to admin_url.env
if [[ "$userreg" != *"User registration failed."* ]]; then
  echo "User registration successful."
  echo "ADMINURL=$userreg" > admin_url.env
fi
