#!/bin/bash

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

exec 1>&2

systemctl --user try-restart \
    passbolt.service \
    passbolt-db.service \
    passbolt-app.service
