#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

config = {}

with open("config.json", 'r') as fp:
    config = json.load(fp)

json.dump(config, fp=sys.stdout)
